version: '3'
services: 
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - my-network

  frontend: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
