apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
spec:
  selector:
    matchLabels:
      app: fe
  replicas: 3
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - name: fe
          image: fe
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  ports:
    - port: 5173
      targetPort: 5173
  selector:
    app: fe
  type: NodePort
